wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: DQN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10000
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715586704
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
